import type {
  LoadingType,
  NavLeftType,
  AboutType,
  SkillsType,
  ExperienceType,
  WorksType,
} from '@/types';
import { WorksCategoryEnum } from '@/types';

export const categoryList = [
  {
    key: WorksCategoryEnum.ALL,
    text: 'TAB__ALL',
  },
  {
    key: WorksCategoryEnum.WORK,
    text: 'TAB__WORK',
  },
  {
    key: WorksCategoryEnum.SIDE_PROJECT,
    text: 'TAB__SIDE_PROJECT',
  },
];

export const loading: LoadingType = {
  name: 'LOADING__NAME',
  position: 'LOADING__POSITION',
};

export const navLeft: NavLeftType = {
  links: [
    {
      url: 'mailto:rosewang0303@gmail.com?subject=[Rose作品集] 回覆聯絡',
      img: '/assets/icon/envelope.svg',
      text: 'rosewang0303@gmail.com',
    },
    {
      url: 'https://github.com/rosewang0303',
      img: '/assets/icon/github.svg',
      text: 'GitHub',
    },
    {
      url: 'https://www.linkedin.com/in/wangrose',
      img: '/assets/icon/linkin.svg',
      text: 'LinkedIn',
    },
    {
      url: 'https://codepen.io/rosewang0303',
      img: '/assets/icon/codepen.svg',
      text: 'Codepen',
    },
  ],
};

export const about: AboutType = {
  name: 'ABOUT__NAME',
  position: 'ABOUT__POSITION',
  introduce: 'ABOUT__INTRODUCE',

  links: [
    { text: 'ABOUT__SKILLS', link: '/#skills' },
    { text: 'ABOUT__EXPERIENCE', link: '/#experience' },
    { text: 'ABOUT__WORKS', link: '/#works' },
    // { text: 'CONTACT', link: '/#contact' },
  ],
};

export const skills: SkillsType = {
  title: 'SKILLS__TITLE',
  description: 'SKILLS__DESCRIPTION',
  items: [
    {
      name: 'SKILLS__ITEMS_1__NAME',
      skill: [
        'SKILLS__ITEMS_1__SKILL_1',
        'SKILLS__ITEMS_1__SKILL_2',
        null,
        'SKILLS__ITEMS_1__SKILL_3',
        'SKILLS__ITEMS_1__SKILL_4',
        'SKILLS__ITEMS_1__SKILL_5',
        null,
        'SKILLS__ITEMS_1__SKILL_6',
        'SKILLS__ITEMS_1__SKILL_7',
        'SKILLS__ITEMS_1__SKILL_8',
        'SKILLS__ITEMS_1__SKILL_9',
        'SKILLS__ITEMS_1__SKILL_10',
        'SKILLS__ITEMS_1__SKILL_11',
        null,
        'SKILLS__ITEMS_1__SKILL_12',
        'SKILLS__ITEMS_1__SKILL_13',
        'SKILLS__ITEMS_1__SKILL_14',
        'SKILLS__ITEMS_1__SKILL_15',
        null,
        'SKILLS__ITEMS_1__SKILL_16',
      ],
    },
    {
      name: 'SKILLS__ITEMS_2__NAME',
      skill: [
        'SKILLS__ITEMS_2__SKILL_1',
        'SKILLS__ITEMS_2__SKILL_2',
        'SKILLS__ITEMS_2__SKILL_3',
        'SKILLS__ITEMS_2__SKILL_4',
        null,
        'SKILLS__ITEMS_2__SKILL_5',
        'SKILLS__ITEMS_2__SKILL_6',
      ],
    },
    {
      name: 'SKILLS__ITEMS_3__NAME',
      skill: [
        'SKILLS__ITEMS_3__SKILL_1',
        null,
        'SKILLS__ITEMS_3__SKILL_2',
        'SKILLS__ITEMS_3__SKILL_3',
        null,
        'SKILLS__ITEMS_3__SKILL_4',
        'SKILLS__ITEMS_3__SKILL_5',
        null,
        'SKILLS__ITEMS_3__SKILL_6',
        'SKILLS__ITEMS_3__SKILL_7',
      ],
    },
    {
      name: 'SKILLS__ITEMS_4__NAME',
      skill: [
        'SKILLS__ITEMS_4__SKILL_1',
        null,
        'SKILLS__ITEMS_4__SKILL_2',
        null,
        'SKILLS__ITEMS_4__SKILL_3',
        'SKILLS__ITEMS_4__SKILL_4',
        'SKILLS__ITEMS_4__SKILL_5',
        'SKILLS__ITEMS_4__SKILL_6',
        null,
        'SKILLS__ITEMS_4__SKILL_7',
      ],
    },
  ],
};

export const experience: ExperienceType = {
  title: 'EXPERIENCE__TITLE',
  subTitle: '(6+y)',
  description: 'EXPERIENCE__DESCRIPTION',
  list: [
    {
      position: 'EXPERIENCE__1__POSITION',
      company: 'EXPERIENCE__1__COMPANY',
      time: '2022/04 ~ 2025/03 (3y)',
      project: [
        'EXPERIENCE__1__PROJECT_1',
        'EXPERIENCE__1__PROJECT_2',
        'EXPERIENCE__1__PROJECT_3',
        'EXPERIENCE__1__PROJECT_4',
        'EXPERIENCE__1__PROJECT_5',
        'EXPERIENCE__1__PROJECT_6',
        // '使用 Nuxt.js 與 Vue.js 開發多款手遊的行銷網站、預約註冊頁面、遊戲內高互動活動頁，以及多套內部後台管理系統的開發與維護',
        // '參與公司多款熱門手遊相關網頁開發，包括「傳說對決」、「DeltaForce」、「天涯明月刀M」、「決勝時刻：Mobile」、「黑色五葉草M 魔法帝之道」、「黎明覺醒」、「鋼之鍊金術師M」等專案',
        // '面對百萬等級用戶流量，進行高效能資料渲染與 UX 優化，確保網站穩定性與使用體驗',
        // '開發 SSR 架構網站並進行 SEO 優化，支援各大社群平台分享與預覽顯示',
        // '實作 RWD 響應式設計，支援跨裝置與 In-App WebView，確保網站在 iOS、Android 各型裝置及平板上正常運行，並透過 BrowserStack 處理跨設備相容性 bug',
        // '與美術設計師協作，處理美術特效動畫與音效素材，協助切圖與素材整合',
        // '與前端團隊協同開發，進行 Code Review，透過 Eslint、Prettier 與 TypeScript 統一程式風格，維護程式碼品質並促進團隊技術交流',
        // '與後端工程師密切合作，討論 API 設計並進行串接，規劃前後端協作的最佳技術解決方案',
        // '配合 QA 測試進行 Bug 修復與優化，使用 Jira 管理任務與測試流程',
        // '參與跨國遊戲營運團隊會議，與 PM 共同討論技術可行性、專案時程規劃及後續版本維護策略',
        // '使用 Sentry 監控網站狀況，處理例外錯誤，並在大量用戶同時上線的情境下快速修復錯誤並部署更新',
        // '積極參與部門內部技術分享會與業界前端交流會，研究並導入新技術提升開發效率與品質',
        // '開發並維護部門共用的 Storybook 元件庫，使用 cookiecutter（Django 工具）撰寫可重用的專案模板',
        // '撰寫並維護開發文件與內部技術手冊，提升團隊知識傳承與開發效率',
        // '具備遠端協作經驗，在疫情期間持續維持高產出，同時也能適應現場辦公環境',
      ],
      tags: [
        // 前端核心
        'EXPERIENCE__1__TAGS_1',
        'EXPERIENCE__1__TAGS_2',
        'EXPERIENCE__1__TAGS_3',
        'EXPERIENCE__1__TAGS_4',
        'EXPERIENCE__1__TAGS_5',
        'EXPERIENCE__1__TAGS_6',
        'EXPERIENCE__1__TAGS_7',
        'EXPERIENCE__1__TAGS_8',
        'EXPERIENCE__1__TAGS_9',
        // 程式品質與開發協作
        'EXPERIENCE__1__TAGS_10',
        'EXPERIENCE__1__TAGS_11',
        'EXPERIENCE__1__TAGS_12',
        'EXPERIENCE__1__TAGS_13',
        'EXPERIENCE__1__TAGS_14',
        'EXPERIENCE__1__TAGS_15',
        'EXPERIENCE__1__TAGS_16',
        // 效能監控與跨裝置測試
        'EXPERIENCE__1__TAGS_17',
        'EXPERIENCE__1__TAGS_18',
        'EXPERIENCE__1__TAGS_19',
        'EXPERIENCE__1__TAGS_20',
        // SEO 與行銷追蹤
        'EXPERIENCE__1__TAGS_21',
        'EXPERIENCE__1__TAGS_22',
        'EXPERIENCE__1__TAGS_23',
        'EXPERIENCE__1__TAGS_24',
        'EXPERIENCE__1__TAGS_25',
      ],
    },
    {
      position: 'EXPERIENCE__2__POSITION',
      company: 'EXPERIENCE__2__COMPANY',
      time: '2019/12 ~ 2022/04 (2y5m)',
      project: [
        'EXPERIENCE__2__PROJECT_1',
        'EXPERIENCE__2__PROJECT_2',
        'EXPERIENCE__2__PROJECT_3',
        'EXPERIENCE__2__PROJECT_4',
        'EXPERIENCE__2__PROJECT_5',
        // '研究區塊鏈相關技術，使用 Solidity 撰寫以太坊智能合約並完成上鏈流程，設計交易互動 API，並透過 Web3.js 與區塊鏈錢包進行整合與串接',
        // '參與專案初期構思與發想，針對應用情境進行技術可行性分析與實作開發',
        // '進行前端 RWD 響應式開發，串接內部與第三方 API（包含金流服務），並與其他前端工程師協同合作',
        // '與 UI/UX 設計師密切合作，優化操作體驗，依據 Sketch 與 Zeplin 設計稿實作高還原度介面',
        // '依據行銷需求進行使用行為追蹤，埋設 Google Analytics 與 Google Conversion，並規劃後台埋點邏輯與資料結構',
        // '部分專案參與後端資料庫規劃與 API 設計與撰寫，具備前後端協作實戰經驗',
        // '具備長期遠端協作經驗，疫情期間由 on-site 辦公轉為 remote 協作，持續維持高效產出與流暢溝通，確保跨部門開發流程順利執行',
      ],
      tags: [
        'EXPERIENCE__2__TAGS_1',
        'EXPERIENCE__2__TAGS_2',
        'EXPERIENCE__2__TAGS_3',
        'EXPERIENCE__2__TAGS_4',
        'EXPERIENCE__2__TAGS_5',
        'EXPERIENCE__2__TAGS_6',
        'EXPERIENCE__2__TAGS_7',
        'EXPERIENCE__2__TAGS_8',
        'EXPERIENCE__2__TAGS_9',
        'EXPERIENCE__2__TAGS_10',
        'EXPERIENCE__2__TAGS_11',
        'EXPERIENCE__2__TAGS_12',
        'EXPERIENCE__2__TAGS_13',
        'EXPERIENCE__2__TAGS_14',
      ],
    },
    {
      position: 'EXPERIENCE__3__POSITION',
      company: 'EXPERIENCE__3__COMPANY',
      time: '2019 ~ 2021',
      project: [
        'EXPERIENCE__3__PROJECT_1',
        'EXPERIENCE__3__PROJECT_2',
        'EXPERIENCE__3__PROJECT_3',
        'EXPERIENCE__3__PROJECT_4',
        'EXPERIENCE__3__PROJECT_5',
      ],
      tags: [
        'EXPERIENCE__3__TAGS_1',
        'EXPERIENCE__3__TAGS_2',
        'EXPERIENCE__3__TAGS_3',
        'EXPERIENCE__3__TAGS_4',
        'EXPERIENCE__3__TAGS_5',
        'EXPERIENCE__3__TAGS_6',
        'EXPERIENCE__3__TAGS_7',
        'EXPERIENCE__3__TAGS_8',
        'EXPERIENCE__3__TAGS_9',
        'EXPERIENCE__3__TAGS_10',
      ],
    },
    {
      position: 'EXPERIENCE__4__POSITION',
      company: 'EXPERIENCE__4__COMPANY',
      time: '2018/08 ~ 2019/07 (1y)',
      project: [
        'EXPERIENCE__4__PROJECT_1',
        'EXPERIENCE__4__PROJECT_2',
        'EXPERIENCE__4__PROJECT_3',
        'EXPERIENCE__4__PROJECT_4',
        'EXPERIENCE__4__PROJECT_5',
      ],
      tags: [
        'EXPERIENCE__4__TAGS_1',
        'EXPERIENCE__4__TAGS_2',
        'EXPERIENCE__4__TAGS_3',
        'EXPERIENCE__4__TAGS_4',
        'EXPERIENCE__4__TAGS_5',
        'EXPERIENCE__4__TAGS_6',
        'EXPERIENCE__4__TAGS_7',
        'EXPERIENCE__4__TAGS_8',
        'EXPERIENCE__4__TAGS_9',
        'EXPERIENCE__4__TAGS_10',
        'EXPERIENCE__4__TAGS_11',
        'EXPERIENCE__4__TAGS_12',
        'EXPERIENCE__4__TAGS_13',
        'EXPERIENCE__4__TAGS_14',
      ],
    },

    {
      position: 'EXPERIENCE__5__POSITION',
      company: 'EXPERIENCE__5__COMPANY',
      time: '2018/02 ~ 2018/06  (5m)',
      project: [
        'EXPERIENCE__5__PROJECT_1',
        'EXPERIENCE__5__PROJECT_2',
        'EXPERIENCE__5__PROJECT_3',
        'EXPERIENCE__5__PROJECT_4',
      ],
      tags: [
        'EXPERIENCE__5__TAGS_1',
        'EXPERIENCE__5__TAGS_2',
        'EXPERIENCE__5__TAGS_3',
        'EXPERIENCE__5__TAGS_4',
        'EXPERIENCE__5__TAGS_5',
        'EXPERIENCE__5__TAGS_6',
        'EXPERIENCE__5__TAGS_7',
        'EXPERIENCE__5__TAGS_8',
        'EXPERIENCE__5__TAGS_9',
      ],
    },
    {
      position: 'EXPERIENCE__6__POSITION',
      company: 'EXPERIENCE__6__COMPANY',
      time: '2014/09 ~ 2018/06 (4y)',
      project: ['EXPERIENCE__6__PROJECT_1', 'EXPERIENCE__6__PROJECT_2'],
      tags: [
        'EXPERIENCE__6__TAGS_1',
        'EXPERIENCE__6__TAGS_2',
        'EXPERIENCE__6__TAGS_3',
        'EXPERIENCE__6__TAGS_4',
        'EXPERIENCE__6__TAGS_5',
        'EXPERIENCE__6__TAGS_6',
        'EXPERIENCE__6__TAGS_7',
      ],
    },
  ],
};

export const works: WorksType = {
  title: 'WORKS__TITLE',
  description: 'WORKS__DESCRIPTION',
  lang: {
    name: 'WORKS__PROJECTS__NAME_',
    date: 'WORKS__PROJECTS__DATE_',
    description: 'WORKS__PROJECTS__DESCRIPTION_',
    skillsPrefix: 'WORKS__PROJECTS__SKILLS_',
    tagsPrefix: 'WORKS__PROJECTS__TAGS_',
  },

  projects: [
    {
      id: 25101,
      category: WorksCategoryEnum.WORK,
      skillsCount: 12,
      tagsCount: 11,
      demoImgs: ['/assets/works/fam_preregister.png'],
      imgs: ['/assets/works/deltaforce.png', '/assets/works/fam_preregister.png'],
      demoLinks: [
        {
          link: 'https://deltaforce.garena.com/en/?redirect=0',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
    },
    {
      id: 25102,
      category: WorksCategoryEnum.WORK,
      skillsCount: 15,
      tagsCount: 8,
      demoImgs: [
        '/assets/works/mbm_bingo.png',
        '/assets/works/aov_psschesttem.png',
        '/assets/works/aov_supersale.png',
      ],
      imgs: [
        '/assets/works/mbm_bingo.png',
        '/assets/works/aov_psschesttem.png',
        '/assets/works/aov_supersale.png',
        '/assets/works/aov_grouping_topup.png',
        '/assets/works/codm_doftem.png',
        '/assets/works/aov_towerchest_hunter_ip.png',
        '/assets/works/aov_vdiscount.jpg',
        '/assets/works/bcm_golbalworldmatch.png',
        '/assets/works/bcm_golbalworldmatch_2.png',
        '/assets/works/bcm_mysteryshop.png',
        '/assets/works/ud_option_panel.png',
        '/assets/works/aov_skin_grading.jpg',
      ],
    },
    {
      id: 22101,
      category: WorksCategoryEnum.WORK,
      skillsCount: 11,
      tagsCount: 8,
      demoImgs: ['/assets/works/shop.png', '/assets/works/shop_2.png'],
      imgs: ['/assets/works/shop.png', '/assets/works/shop_2.png'],
      demoLinks: [
        {
          link: 'https://www.shop168.fun/',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
    },
    {
      id: 21201,
      category: WorksCategoryEnum.SIDE_PROJECT,
      skillsCount: 5,
      tagsCount: 7,
      demoImgs: ['/assets/works/youbike_map.png'],
      imgs: ['/assets/works/youbike_map.png'],
      demoLinks: [
        {
          link: 'https://youbike-map.netlify.app/',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
      github: 'https://github.com/rosewang0303/youbike-map',
    },
    {
      id: 21202,
      category: WorksCategoryEnum.SIDE_PROJECT,
      skillsCount: 5,
      tagsCount: 5,
      demoImgs: ['/assets/works/taiwan_spots.png'],
      imgs: ['/assets/works/taiwan_spots.png'],
      demoLinks: [
        {
          link: 'https://taiwan-spots.netlify.app/',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
      github: 'https://github.com/rosewang0303/taiwan-spots',
    },
    {
      id: 23101,
      category: WorksCategoryEnum.SIDE_PROJECT,
      skillsCount: 2,
      tagsCount: 3,
      demoImgs: ['/assets/works/phaser_game.png'],
      imgs: ['/assets/works/phaser_game.png'],
      demoLinks: [
        {
          link: 'https://codepen.io/garena-tw-eng/full/oNPGpBj',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
    },
    {
      id: 22102,
      category: WorksCategoryEnum.WORK,
      skillsCount: 10,
      tagsCount: 7,
      demoImgs: ['/assets/works/tracke.png'],
      imgs: ['/assets/works/tracke.png'],
    },
    {
      id: 25203,
      category: WorksCategoryEnum.SIDE_PROJECT,
      skillsCount: 6,
      tagsCount: 5,
      demoImgs: ['/assets/works/staking_game.png'],
      imgs: ['/assets/works/staking_game.png'],
      // demoLinks: [
      //   {
      //     link: '',
      //     text: '', // WORKS__DEMO_LINKS
      //   },
      // ],
    },
    {
      id: 20201,
      category: WorksCategoryEnum.SIDE_PROJECT,
      skillsCount: 4,
      tagsCount: 5,
      demoImgs: ['/assets/works/travel_planner.png'],
      imgs: ['/assets/works/travel_planner.png'],
      demoLinks: [
        {
          link: 'https://travel-planner-gogo.netlify.app/',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
    },
    {
      id: 220201,
      category: WorksCategoryEnum.SIDE_PROJECT,
      skillsCount: 4,
      tagsCount: 4,
      demoImgs: ['/assets/works/live_stream.png'],
      imgs: ['/assets/works/live_stream.png'],
      demoLinks: [
        {
          link: 'https://live-stream-chat.netlify.app/',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
      github: 'https://github.com/rosewang0303/live-stream',
    },
    {
      id: 210203,
      category: WorksCategoryEnum.SIDE_PROJECT,
      skillsCount: 4,
      tagsCount: 5,
      demoImgs: ['/assets/works/bus_timetable.png'],
      imgs: ['/assets/works/bus_timetable.png'],
      demoLinks: [
        {
          link: 'https://taiwan-bus-timetable.netlify.app/',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
      github: 'https://github.com/rosewang0303/bus-timetable',
    },
    {
      id: 220102,
      category: WorksCategoryEnum.WORK,
      skillsCount: 5,
      tagsCount: 2,
      demoImgs: ['/assets/works/vending_machines.png'],
      imgs: ['/assets/works/vending_machines.png'],
    },
    {
      id: 190101,
      category: WorksCategoryEnum.WORK,
      skillsCount: 5,
      tagsCount: 4,
      demoImgs: ['/assets/works/altc.png'],
      imgs: ['/assets/works/altc.png'],
      demoLinks: [
        {
          link: 'https://www.airltc.com/',
          text: 'WORKS__DEMO_LINKS',
        },
      ],
    },
    {
      id: 190102,
      category: WorksCategoryEnum.WORK,
      skillsCount: 6,
      tagsCount: 7,
      demoImgs: ['/assets/works/taoyuan.png', '/assets/works/taoyuan_2.png'],
      imgs: ['/assets/works/taoyuan.png', '/assets/works/taoyuan_2.png'],
    },
    {
      id: 190103,
      category: WorksCategoryEnum.WORK,
      skillsCount: 5,
      tagsCount: 6,
      demoImgs: ['/assets/works/taichung.png', '/assets/works/taichung_2.png'],
      imgs: ['/assets/works/taichung.png', '/assets/works/taichung_2.png'],
    },
  ],
};

export const brandLogoList: Array<string> = [
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vuejs/vuejs-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nuxtjs/nuxtjs-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-plain-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/gitlab/gitlab-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sketch/sketch-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/npm/npm-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bun/bun-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-line-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/axios/axios-plain.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/slack/slack-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/yarn/yarn-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/webpack/webpack-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/electron/electron-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jquery/jquery-plain-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/netlify/netlify-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/codepen/codepen-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/solidity/solidity-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jira/jira-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/swift/swift-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/photoshop/photoshop-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/illustrator/illustrator-plain.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/eslint/eslint-plain-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cypressio/cypressio-original.svg',
];
