import type {
  LoadingType,
  NavLeftType,
  AboutType,
  SkillsType,
  ExperienceType,
  WorksType,
} from '@/types';
import { WorksCategoryEnum } from '@/types';

export const loading: LoadingType = {
  name: 'ROSE WANG',
  position: 'Front-End Engineer / Software Engineer',
};

export const navLeft: NavLeftType = {
  links: [
    {
      url: 'mailto:rosewang0303@gmail.com?subject=[Rose作品集] 回覆聯絡',
      img: '/assets/icon/envelope.svg',
      text: 'rosewang0303@gmail.com',
    },
    {
      url: 'https://github.com/rosewang0303',
      img: '/assets/icon/github.svg',
      text: 'GitHub',
    },
    {
      url: 'https://www.linkedin.com/in/rose-wang-9577631b8/',
      img: '/assets/icon/linkin.svg',
      text: 'LinkedIn',
    },
    {
      url: 'https://codepen.io/rosewang0303',
      img: '/assets/icon/codepen.svg',
      text: 'Codepen',
    },
  ],
};

export const about: AboutType = {
  name: 'ROSE WANG',
  position: 'Front-End Engineer / Software Engineer',
  introduce:
    '專注打造具備<span>視覺吸引力與互動細節</span>的網頁體驗。我是從全端轉向前端的開發者，擁有超過 6 年軟體開發經驗，擅長將動畫特效與使用者體驗結合，追求技術與美感兼具的產品呈現。',
  links: [
    { text: 'SKILLS', link: '/#skills' },
    { text: 'EXPERIENCE', link: '/#experience' },
    { text: 'WORKS', link: '/#works' },
    // { text: 'CONTACT', link: '/#contact' },
  ],
};

export const skills: SkillsType = {
  title: 'SKILLS',
  description:
    '擅長 Vue.js 生態系開發，熟悉使用 Nuxt.js 進行 SSR 開發，並持續學習 React.js 等前端技術。具備 GSAP 等動畫庫應用經驗，亦具備基本的設計工具操作能力（Figma、Photoshop、Illustrator）。具備完整後端開發背景，熟悉 PHP、Java、C# 等語言，亦曾探索區塊鏈技術，撰寫並部署 Solidity 智能合約。具備 iOS App 開發與上架經驗，並曾開發 Google Chrome Extension、LINE LIFF、Electron.js 等多項 Side Project。',
  items: [
    {
      name: '前端技術 & 框架',
      skill: [
        '<span>Vue.js / Nuxt.js (SSR)</span>',
        '<span>Pinia / Vuex / VueUse</span>',
        null,
        '<span>RWD / In-APP-Webview</span>',
        '<span>SASS (SCSS) / Tailwind / BEM</span>',
        '<span>Javascript / TypeScript</span>',
        null,
        'Cypress',
        'Vite',
        'Webpack',
        'Yarn / bun / npm',
        'Eslint / Prettier',
        'SEO',
        null,
        'Electron.js',
        'LINE Front-end Framework (LIFF)',
        'Google Chrome Extension',
        'Element UI',
        null,
        'jQuery / Bootstrap',
      ],
    },
    {
      name: '後端經驗',
      skill: [
        '<span>Node.js (Express)</span>',
        'PHP (Laravel)',
        null,
        'mySQL',
        'API 開發',
        '系統 & 資料庫設計',
      ],
    },
    {
      name: '團隊合作 / 工具',
      skill: [
        'Git (Github / Gitlab)',
        null,
        '<span>Figma</span>',
        'Zeplin / Sketch',
        null,
        'Jira',
        'Slack',
      ],
    },
    {
      name: '其他實戰經驗 / 興趣延伸',
      skill: [
        'PS / AI',
        null,
        'Web3.js / Solidity (Block chain)',
        null,
        'Phaser.js / Chart.js',
        '<span>GSAP</span>',
        '<span>Matter.js</span>',
        null,
        'iOS APP (Swift)',
      ],
    },
  ],
};

export const experience: ExperienceType = {
  title: 'EXPERIENCE',
  subTitle: '(6+y)',
  description:
    '擁有超過 6 年軟體開發經驗，從全端開發起步，累積前後端協作與系統設計能力，後專注於前端領域，深入 Vue.js 生態系並持續精進技術與使用者體驗。曾參與大型企業多人協作與系統維運，也在新創團隊中主導產品從 0 到 1 的開發與上線。具備跨領域溝通能力與遠端/現場的彈性協作經驗，能靈活應對不同開發環境與團隊需求。',
  list: [
    {
      position: '前端工程師',
      company: '@新加坡商競舞電競有限公司 (Garena)',
      time: '2022/04 ~ 2025/03 (3y)',
      project: [
        '使用 Nuxt.js、Vue.js 開發多款知名手遊的行銷活動網站、預約註冊頁面與遊戲內高互動網頁活動（如：傳說對決、天涯明月刀M、黑色五葉草M 等）',
        '負責前端系統開發與維護，包含網站效能優化、RWD、In-App WebView 支援、SEO 整合與跨裝置相容性調整',
        '與 UI/UX 設計、後端、QA、PM 協作，從 API 串接到跨部門技術規劃，推進專案如期上線',
        '管理大型用戶量環境下的例外處理與監控，使用 Sentry 快速回應錯誤並部署修復',
        '推動團隊技術品質，參與 Code Review、共用元件開發（Storybook）、並撰寫維護開發文件與專案模板',
        // '使用 Nuxt.js 與 Vue.js 開發多款手遊的行銷網站、預約註冊頁面、遊戲內高互動活動頁，以及多套內部後台管理系統的開發與維護',
        // '參與公司多款熱門手遊相關網頁開發，包括「傳說對決」、「DeltaForce」、「天涯明月刀M」、「決勝時刻：Mobile」、「黑色五葉草M 魔法帝之道」、「黎明覺醒」、「鋼之鍊金術師M」等專案',
        // '面對百萬等級用戶流量，進行高效能資料渲染與 UX 優化，確保網站穩定性與使用體驗',
        // '開發 SSR 架構網站並進行 SEO 優化，支援各大社群平台分享與預覽顯示',
        // '實作 RWD 響應式設計，支援跨裝置與 In-App WebView，確保網站在 iOS、Android 各型裝置及平板上正常運行，並透過 BrowserStack 處理跨設備相容性 bug',
        // '與美術設計師協作，處理美術特效動畫與音效素材，協助切圖與素材整合',
        // '與前端團隊協同開發，進行 Code Review，透過 Eslint、Prettier 與 TypeScript 統一程式風格，維護程式碼品質並促進團隊技術交流',
        // '與後端工程師密切合作，討論 API 設計並進行串接，規劃前後端協作的最佳技術解決方案',
        // '配合 QA 測試進行 Bug 修復與優化，使用 Jira 管理任務與測試流程',
        // '參與跨國遊戲營運團隊會議，與 PM 共同討論技術可行性、專案時程規劃及後續版本維護策略',
        // '使用 Sentry 監控網站狀況，處理例外錯誤，並在大量用戶同時上線的情境下快速修復錯誤並部署更新',
        // '積極參與部門內部技術分享會與業界前端交流會，研究並導入新技術提升開發效率與品質',
        // '開發並維護部門共用的 Storybook 元件庫，使用 cookiecutter（Django 工具）撰寫可重用的專案模板',
        // '撰寫並維護開發文件與內部技術手冊，提升團隊知識傳承與開發效率',
        // '具備遠端協作經驗，在疫情期間持續維持高產出，同時也能適應現場辦公環境',
      ],
      tags: [
        // 前端核心
        'Nuxt.js',
        'Vue.js',
        'TypeScript',
        'CSS（SCSS）',
        'Vite',
        'Webpack',
        'SSR',
        'RWD',
        'WebView',
        // 程式品質與開發協作
        'Eslint',
        'Prettier',
        'Storybook',
        'cookie-cutter（Django）',
        'Jira',
        'Git',
        'Code Review',
        // 效能監控與跨裝置測試
        'Sentry',
        'Browser Stack',
        '跨裝置相容性調整',
        '百萬用戶效能優化',
        // SEO 與行銷追蹤
        'SEO',
        'Google Analytics',
        'Google Conversion',
        'Meta Pixel',
        'TikTok Pixel',
      ],
    },
    {
      position: '全端工程師 → 前端工程師 (遠端)',
      company: '@紫洣科技股份有限公司',
      time: '2019/12 ~ 2022/04 (2y5m)',
      project: [
        '使用 Nuxt.js、Vue.js 與 Laravel（PHP） 負責多個專案的前端及部分後端開發，包括電商平台、區塊鏈交易平台、智能販賣機、內部後台等',
        '研究並開發區塊鏈應用，撰寫以太坊智能合約（Solidity）、交易 API，整合 Web3.js 及錢包功能',
        '與設計師依照 Zeplin、Sketch 合作開發 UI，並依需求調整 RWD、UX 流程',
        '串接第三方 API（包含金流）、規劃 Google Analytics 與轉換追蹤，實作後台埋點邏輯',
        '參與專案從 0 到 1 的技術規劃、跨部門討論與後續維運',
        // '研究區塊鏈相關技術，使用 Solidity 撰寫以太坊智能合約並完成上鏈流程，設計交易互動 API，並透過 Web3.js 與區塊鏈錢包進行整合與串接',
        // '參與專案初期構思與發想，針對應用情境進行技術可行性分析與實作開發',
        // '進行前端 RWD 響應式開發，串接內部與第三方 API（包含金流服務），並與其他前端工程師協同合作',
        // '與 UI/UX 設計師密切合作，優化操作體驗，依據 Sketch 與 Zeplin 設計稿實作高還原度介面',
        // '依據行銷需求進行使用行為追蹤，埋設 Google Analytics 與 Google Conversion，並規劃後台埋點邏輯與資料結構',
        // '部分專案參與後端資料庫規劃與 API 設計與撰寫，具備前後端協作實戰經驗',
        // '具備長期遠端協作經驗，疫情期間由 on-site 辦公轉為 remote 協作，持續維持高效產出與流暢溝通，確保跨部門開發流程順利執行',
      ],
      tags: [
        'Vue.js',
        'Nuxt.js',
        'PHP',
        'Laravel',
        'Web3.js',
        'Solidity',
        'SCSS',
        'Bootstrap',
        'jQuery',
        'Google Analytics',
        'Google Conversion',
        'Git',
        'Sketch',
        'Zeplin',
      ],
    },
    {
      position: '前端工程師 (遠端)',
      company: '@個人接案',
      time: '2019 ~ 2021',
      project: [
        '獨立承接專案，負責與客戶簽約、需求訪談、專案規劃與時程安排，完整執行至交付與結案',
        '開發客製化後台管理系統，負責前端畫面與功能實作',
        '依據客戶需求調整與修改 Google Blogger 模板，優化版面與功能結構',
        '負責前端 RWD 響應式設計與開發，確保跨裝置瀏覽體驗一致',
        '與後端工程師協作串接 API，處理資料互動與呈現',
      ],
      tags: [
        'Vue.js',
        'JavaScript',
        'CSS',
        'jQuery',
        'Ajax',
        'RWD',
        'API 串接',
        'Blogger 模板客製',
        '接案經驗',
        '專案規劃',
      ],
    },
    {
      position: '全端工程師',
      company: '@諾亞克科技股份有限公司',
      time: '2018/08 ~ 2019/07 (1y)',
      project: [
        '負責開發 ERP 系統、長照醫療系統與醫療設備專用 App，涵蓋企業與醫療場域應用',
        '負責前後端全端開發，包括資料庫設計、後端 API 開發與前端頁面實作',
        '開發 RWD 響應式前端頁面，支援跨裝置瀏覽體驗',
        '主導專案從 0 到 1 的技術規劃，參與跨部門溝通與開發流程設計，並持續進行後續維護與功能優化',
        '實地面對第一線客戶，了解需求並協助轉化為可行的技術方案',
      ],
      tags: [
        'PHP',
        'Laravel',
        'C#',
        '.NET Framework',
        'JavaScript',
        'CSS',
        'jQuery',
        'Ajax',
        'RWD',
        '全端開發',
        '資料庫設計',
        'API 開發',
        '跨部門協作',
        '需求訪談',
      ],
    },

    {
      position: '程式設計實習生',
      company: '@國泰金融控股股份有限公司',
      time: '2018/02 ~ 2018/06  (5m)',
      project: [
        '開發金融後台系統與部門內部使用工具，支援日常營運與流程優化',
        '依據 SA / SD 提出的工單需求進行後端模組開發與維護',
        '開發與串接後端 API，實作資料流程邏輯',
        '負責前端介面切版與 API 串接，實現資料互動功能',
      ],
      tags: [
        'Java',
        'JSP',
        'JavaScript',
        'jQuery',
        'CSS',
        'Ajax',
        '後台系統',
        'API 開發',
        '系統模組化',
      ],
    },
    {
      position: '資訊管理學系 學士',
      company: '@東海大學',
      time: '2014/09 ~ 2018/06 (4y)',
      project: [
        '大學期間修習多門資訊與商業相關課程，建立紮實的程式設計與邏輯思維基礎',
        '核心課程包含程式設計、資料庫規劃、統計學、離散數學、會計學、資訊管理與微積分',
      ],
      tags: ['Python', 'Java', 'JavaScript', 'PHP', 'C', 'C#', '資料庫設計'],
    },
  ],
};

export const works: WorksType = {
  title: 'WORKS',
  description:
    '除了職務開發之外，也熱衷研究新技術並將生活中的痛點轉化為 Side Project。具備後端經驗，能獨立完成全端開發，從 UI/UX 設計到功能落地皆能自主實作，打造具備技術深度與良好體驗的作品。對設計與視覺美感有濃厚興趣，雖非專業設計師，卻重視細節與整體畫面，希望在使用者體驗與視覺效果間取得最佳平衡。',
  projects: [
    {
      id: 25101,
      name: '遊戲行銷網站',
      category: WorksCategoryEnum.WORK,
      date: '2022~2025 年',
      skills: [
        '開發「DeltaForce」、「鋼之鍊金術師M」...等多款遊戲行銷網站',
        '使用 Nuxt.js（Vue SSR 框架） 進行前端開發，建構 SEO 友善且效能良好的網站架構',
        '實作 響應式 RWD 網頁，搭配 SASS(SCSS) 進行樣式模組化開發，並導入 TypeScript 強化程式碼穩定性與可維護性',
        '整合 i18n 國際化套件，實現多語系切換功能以支援全球用戶',
        '參與專案的後續版本維護與新功能開發，持續提升使用者體驗與產品穩定性',
        '跨部門協作：與跨國遊戲營運團隊討論需求與技術可行性，依據工單流程交付專案',
        '與其他前端工程師協作開發並進行 Code Review，共同討論最佳實作方式，持續優化程式碼品質與維持團隊開發一致性',
        '與後端工程師協作 API 設計與串接，確保前後端資料流程順暢',
        '與設計師密切合作，依據 UI 設計稿切版，實作動畫特效與音效觸發邏輯',
        '配合行銷部門需求，整合並設定 GA、Google Conversion、Meta Pixel、TikTok Pixel 等追蹤碼',
        '與 QA 測試工程師協作，針對測試回饋進行問題排查與優化，確保功能穩定與體驗流暢',
        '撰寫並維護開發文件，提升團隊內部知識共享',
      ],
      description:
        '2022 至 2025 年任職於新加坡商競舞電競有限公司（Garena），負責多款遊戲的多國語系行銷官網開發與維護。專案涵蓋遊戲主視覺展示、預註冊活動、公告發布、社群分享等功能，並結合互動式視覺特效，提升玩家參與感。參與從需求討論、前後端串接、UI 實作到後續改版維運等各階段，協助打造具品牌識別與行銷效益的網站體驗。',
      tags: [
        'Nuxt.js (Vue)',
        'Typescript',
        'SASS (SCSS)',
        'Vite',
        'i18n',
        'SSR',
        'SEO',
        'Google Analytics',
        'Google Conversion',
        'Meta Pixel',
        'TikTok Pixel',
      ],
      demoImgs: ['/assets/works/fam_preregister.png'],
      imgs: ['/assets/works/deltaforce.png', '/assets/works/fam_preregister.png'],
      demoLinks: [
        {
          link: 'https://deltaforce.garena.com/en/?redirect=0',
          text: '專案網站',
        },
      ],
    },
    {
      id: 25102,
      name: '手遊 In-App-Webview 互動網頁',
      category: WorksCategoryEnum.WORK,
      date: '2022~2025 年',
      skills: [
        '開發「傳說對決」、「天涯明月刀M」、「決勝時刻：Mobile」、「黑色五葉草M 魔法帝之道」、「黎明覺醒」、「鋼之鍊金術師M」...等多款手遊內互動網頁',
        '使用 Vue.js 開發手遊內 In-App WebView 活動頁，針對 iOS 與 Android 平台進行跨裝置相容性調整',
        '實作 響應式 RWD 網頁，搭配 SASS(SCSS) 進行樣式模組化開發，並導入 TypeScript 強化程式碼穩定性與可維護性',
        '整合 i18n 國際化套件，實現多語系切換功能以支援全球用戶',
        '參與專案的後續版本維護與新功能開發，持續提升使用者體驗與產品穩定性',
        '跨部門協作：與跨國遊戲營運團隊討論需求與技術可行性，依據工單流程交付專案',
        '與其他前端工程師協作開發並進行 Code Review，共同討論最佳實作方式，持續優化程式碼品質與維持團隊開發一致性',
        '與後端工程師協作 API 設計與串接，確保前後端資料流程順暢',
        '與設計師密切合作，依據 UI 設計稿切版，實作動畫特效與音效觸發邏輯',
        '配合行銷部門需求，整合並設定 GA 追蹤碼',
        '與 QA 測試工程師協作，針對測試回饋進行問題排查與優化，確保功能穩定與體驗流暢',
        '面向數百萬玩家，用戶活動高峰期間需支援大量即時在線瀏覽與互動，開發時特別重視效能與穩定性',
        '採用 懶加載（Lazy Loading）、分頁機制與批次請求策略，有效優化資料渲染與用戶操作體驗',
        '整合 WebSocket 即時連線技術，支援玩家於活動頁面中即時互動與參與遊戲機制，提升參與感與趣味性',
        '撰寫並維護開發文件，提升團隊內部知識共享',
      ],
      description:
        '2022 至 2025 年任職於新加坡商競舞電競有限公司（Garena），負責多款手遊的 In-App WebView 活動頁開發與維護。專案涵蓋多國語系支援、視覺特效與互動遊戲設計，內容包括營收向活動頁、IP 聯名合作、遊戲內活動大廳、賽事頁與玩家問卷等，協助提升遊戲黏著度與用戶參與率。',
      tags: [
        'Vue.js',
        'Vue3, Vue2',
        'Typescript',
        'SASS (SCSS)',
        'Vite',
        'In-App-Webview',
        'i18n',
        'Google Analytics',
      ],
      demoImgs: [
        '/assets/works/mbm_bingo.png',
        '/assets/works/aov_psschesttem.png',
        '/assets/works/aov_supersale.png',
      ],
      imgs: [
        '/assets/works/mbm_bingo.png',
        '/assets/works/aov_psschesttem.png',
        '/assets/works/aov_supersale.png',
        '/assets/works/aov_grouping_topup.png',
        '/assets/works/codm_doftem.png',
        '/assets/works/aov_towerchest_hunter_ip.png',
        '/assets/works/aov_vdiscount.jpg',
        '/assets/works/bcm_golbalworldmatch.png',
        '/assets/works/bcm_golbalworldmatch_2.png',
        '/assets/works/bcm_mysteryshop.png',
        '/assets/works/ud_option_panel.png',
        '/assets/works/aov_skin_grading.jpg',
      ],
    },
    {
      id: 22101,
      name: '樂享購 (電商網路購物平台)',
      category: WorksCategoryEnum.WORK,
      date: '2019~2022年',
      skills: [
        '使用 Nuxt.js 和 Vue SSR 框架進行開發，提供高效能的伺服器端渲染 (SSR) 解決方案，並優化 SEO 以提升網站搜尋引擎排名',
        '進行響應式 RWD 網頁開發，並支援主流社群應用程式的 In-App-Webview（如 Line、Facebook 等），搭配 SASS (SCSS) 寫作高效、可維護的程式碼',
        '負責專案的後續改版與新增功能開發，確保持續改進與優化',
        '跨部門協作，參與產品的全程規劃與開發維護',
        '參與團隊會議，與 PM 一同討論並推進產品規劃從概念到上線',
        '與後端工程師合作，設計 API 規格並負責 API 串接',
        '與設計師密切合作，優化 UI/UX，根據 Sketch 和 Zeplin 設計稿進行開發',
        '根據行銷需求埋點，使用 Google Analytics 和 Google Conversion，並設計後台埋點規則',
        '開發互動性網站教學小遊戲，提升用戶體驗',
        '負責購物車結帳流程，並與金流 API 進行串接',
        '與前端團隊合作，共同開發並解決問題',
      ],
      description:
        '2019 至 2022 年於紫洣科技股份有限公司任職，負責該公司開發的電商平台的前端開發，涵蓋整個網站從零到上架的開發與後續維護工作。主要工作包括電商首頁、購物車結帳系統、商品展示、商品分類、促銷活動等多項功能的開發與優化，並針對 SEO 進行優化，提升搜尋引擎的曝光率。',
      tags: [
        'Nuxt.js (Vue)',
        'SASS (SCSS)',
        'SEO',
        'Google Analytics',
        'Google Conversion',
        'In-App-Webview',
        'SSR',
        'SEO',
      ],
      demoImgs: ['/assets/works/shop.png', '/assets/works/shop_2.png'],
      imgs: ['/assets/works/shop.png', '/assets/works/shop_2.png'],
      demoLinks: [
        {
          link: 'https://www.shop168.fun/',
          text: '專案網站',
        },
      ],
    },
    {
      id: 21201,
      name: '自行車道地圖資訊整合網（比賽作品）',
      category: WorksCategoryEnum.SIDE_PROJECT,
      date: '2021 年',
      skills: [
        '使用 Nuxt.js Vue SSR 框架開發，提供高效能的伺服器端渲染 (SSR) 解決方案',
        '串接 Google Maps API 服務，利用 Maps JavaScript API 呈現地圖，並使用 Distance Matrix API 計算位置距離，配合自訂地圖樣式提升用戶體驗',
        '使用 axios 串接 TDX API v2，整合政府 Open Data 服務，提供精確的數據查詢功能',
        '進行響應式 RWD 網頁開發，並搭配 Typescript 和 SASS (SCSS) 撰寫易於維護的程式碼',
        '此專案為參加<a class="cursor-target" href="https://2021.thef2e.com/" target="_blank">「THE F2E 3rd 前端修煉精神時光屋」</a>之比賽作品',
      ],
      description:
        '查詢全台各地自行車站點的車位及路線資訊，顯示自行車的可借還數量，並將資訊於 Google 地圖上呈現，提供便捷的地理位置服務。',
      tags: [
        'Nuxt.js (Vue)',
        'Vuex',
        'google map api',
        'TDX api v2',
        'RWD',
        'Typescript',
        'SASS (SCSS)',
      ],
      demoImgs: ['/assets/works/youbike_map.png'],
      imgs: ['/assets/works/youbike_map.png'],
      demoLinks: [
        {
          link: 'https://youbike-map.netlify.app/',
          text: '專案網站',
        },
      ],
      github: 'https://github.com/rosewang0303/youbike-map',
    },
    {
      id: 21202,
      name: '台灣旅遊景點導覽（比賽作品）',
      category: WorksCategoryEnum.SIDE_PROJECT,
      date: '2021 年',
      skills: [
        '使用 Vue.js 框架進行開發，構建動態與高效的用戶界面',
        '挑戰不依賴第三方套件，親手實作「輪播圖片」功能和「時間選擇器」',
        '使用 axios 串接 TDX API v2 和 v3，並整合政府 Open Data 服務',
        '進行響應式 RWD 網頁開發，並搭配 Typescript 和 SASS (SCSS) 撰寫可維護的程式碼',
        '此專案為參加<a class="cursor-target" href="https://2021.thef2e.com/" target="_blank">「THE F2E 3rd 前端修煉精神時光屋」</a>之比賽作品',
      ],
      description:
        '整合全台各縣市政府舉辦的近期活動、景點導覽與美食店家，並提供使用者根據篩選條件查詢所需資訊。',

      tags: ['Vue.js', 'Vuex', 'google map api', 'TDX api v2, v3', 'RWD'],
      demoImgs: ['/assets/works/taiwan_spots.png'],
      imgs: ['/assets/works/taiwan_spots.png'],
      demoLinks: [
        {
          link: 'https://taiwan-spots.netlify.app/',
          text: '專案網站',
        },
      ],
      github: 'https://github.com/rosewang0303/taiwan-spots',
    },
    {
      id: 22102,
      name: 'Tracke (區塊鏈收藏品交易平台)',
      category: WorksCategoryEnum.WORK,
      date: '2019~2022年',
      skills: [
        '進行前端 RWD 開發，支援多裝置顯示需求，確保一致的用戶體驗',
        '開發多語言網站系統，支援國際化與本地化',
        '負責 API 串接與後續維護，並根據需求開發新功能與改版',
        '與後端工程師協作，撰寫 API 並進行資料庫規劃，確保系統的穩定性與可擴展性',
        '負責後台系統的全端開發，提供完整的管理與運營支持',
        '串接第三方區塊鏈錢包，實現與區塊鏈的無縫互動',
        '開發以太坊智能合約並撰寫 Solidity 合約與交易互動 API，支持區塊鏈交易功能',
        '與設計師合作，根據 Sketch 和 Zeplin 設計稿進行前端開發，確保 UI/UX 的優化',
        '參與團隊會議，與 PM 討論技術可行性並規劃開發時程，確保專案順利進行',
        '解決競拍同步問題，處理交易衝突並確保競拍得標，提升交易流程的穩定性',
      ],
      description:
        '2019 至 2022 年於紫洣科技股份有限公司任職，負責該公司開發的區塊鏈交易平台的前端開發、部分後端 API 撰寫與後台系統開發。參與區塊鏈以太坊智能合約的開發與交易互動撰寫，並開發支持競價拍賣交易、商品展示、商品分類等多種功能。處理競拍同步問題與交易衝突，確保競拍得標並提升整體交易體驗。',
      tags: [
        'Javascript',
        'CSS',
        'Bootstrap',
        '多國語',
        'PHP（Laravel）',
        'Solidity',
        'BlockChain',
      ],
      demoImgs: ['/assets/works/tracke.png'],
      imgs: ['/assets/works/tracke.png'],
    },
    {
      id: 25203,
      name: '推疊小遊戲',
      category: WorksCategoryEnum.SIDE_PROJECT,
      date: '2025 年',
      skills: [
        'Vue.js 開發',
        '獨自規劃專案架構和 UI/UX',
        '利用 Matter.js 來實做物理世界碰撞、重力和堆疊效果',
        '撰寫 CSS（SCSS）樣式和Typescript',
        '串接 API',

        'Node.js（Express）開發後端 API，mySQL，規劃資料庫設計',
      ],
      description:
        '復刻小時候摺疊2G手機的小遊戲，獨自規劃全端開發、資料庫規劃，利用美術素材包來製作像素風格的小遊戲，並利用 Matter.js 來實踐真實世界的物理堆疊和重力。<br><span>[此專案還在開發中]</span>',
      tags: ['Vue.js', 'Matter.js', 'Typescript', 'CSS（SCSS）', 'Node.js（Express）'],
      demoImgs: ['/assets/works/staking_game.png'],
      imgs: ['/assets/works/staking_game.png'],
      demoLinks: [
        {
          link: '',
          text: '專案網站',
        },
      ],
    },
    {
      id: 20201,
      name: '旅遊行程安排小工具',
      category: WorksCategoryEnum.SIDE_PROJECT,
      date: '2020 年',
      skills: [
        '從零開始規劃並開發整個專案，涵蓋 UI/UX 設計及前端實現，根據自身需求與痛點開發專案功能',
        '使用 jQuery 進行前端開發，實現互動性強的功能',
        '特別利用 contextmenu、drag、drop 事件來實作拖放與右鍵菜單等自定義操作，提升使用體驗',
        '進行響應式 RWD 網頁開發，並搭配 Bootstrap 實現快速且一致的界面布局',
      ],
      description:
        '開發了一款簡單易用的旅遊行程規劃工具，旨在幫助用戶安排旅行計劃。該工具支持多款客製化功能，例如自定義 icon 顯示，並可通過拖放操作輕鬆調整行程順序，無限擴展行程天數。此專案的開發源自個人的痛點，致力於提升用戶在規劃行程過程中的便捷性與靈活性。',
      tags: ['Javascript', 'jQuery', 'RWD', 'Bootstrap', 'Font Awesome'],
      demoImgs: ['/assets/works/travel_planner.png'],
      imgs: ['/assets/works/travel_planner.png'],
      demoLinks: [
        {
          link: 'https://travel-planner-gogo.netlify.app/',
          text: '專案網站',
        },
      ],
    },
    {
      id: 220201,
      name: '直播視訊串流',
      category: WorksCategoryEnum.SIDE_PROJECT,
      date: '2022 年',
      skills: [
        '使用 Vue.js 框架進行前端開發，構建動態且高效的用戶界面',
        '從零到一進行 UI/UX 設計及前端規劃，實現直觀且美觀的使用體驗',
        '進行響應式 RWD 網頁開發，確保在各種裝置上提供一致的用戶體驗',
        '利用 GSAP 實現聊天互動動畫，提升用戶互動的趣味性與流暢度',
      ],
      description:
        '開發了一個網頁串流視訊和音訊的專案，使用 navigator.mediaDevices 進行視訊與音訊的串流功能實現，並加入了聊天互動介面。此專案旨在提供一個即時通訊和視訊通話的簡易平台，並透過 GSAP 動畫增強用戶的互動體驗，讓整體操作更加流暢與生動。',
      tags: ['Vue.js', 'RWD', 'navigator.mediaDevices', 'GSAP'],
      demoImgs: ['/assets/works/live_stream.png'],
      imgs: ['/assets/works/live_stream.png'],
      demoLinks: [
        {
          link: 'https://live-stream-chat.netlify.app/',
          text: '專案網站',
        },
      ],
      github: 'https://github.com/rosewang0303/live-stream',
    },
    {
      id: 210203,
      name: '全台公車動態時刻查詢應用服務（比賽作品）',
      category: WorksCategoryEnum.SIDE_PROJECT,
      date: '2021 年',
      skills: [
        '使用 Nuxt.js Vue SSR 框架開發，實現高效能的伺服器端渲染 (SSR)',
        '使用 axios 串接 TDX API v2，整合政府 Open Data 服務，提供即時數據查詢',
        '進行響應式 RWD 網頁開發，並搭配 SASS (SCSS) 撰寫可維護且高效的程式碼',
        '此專案為參加<a class="cursor-target" href="https://2021.thef2e.com/" target="_blank">「THE F2E 3rd 前端修煉精神時光屋」</a>之比賽作品',
      ],
      description:
        '整合全台公車及客運的動態時刻資訊，提供用戶查詢各站點的即時公車及客運運行狀態，並於地圖上顯示各站點的動態站牌。<br>[比賽時間內未完全挑戰成功，功能尚未完整實現]',

      tags: ['Nuxt.js (Vue)', 'Vuex', 'RWD', 'TDX api v2', 'SASS (SCSS) '],
      demoImgs: ['/assets/works/bus_timetable.png'],
      imgs: ['/assets/works/bus_timetable.png'],
      demoLinks: [
        {
          link: 'https://taiwan-bus-timetable.netlify.app/',
          text: '專案網站',
        },
      ],
      github: 'https://github.com/rosewang0303/bus-timetable',
    },

    {
      id: 220102,
      name: '全家超商:智能販賣機',
      category: WorksCategoryEnum.WORK,
      date: '2019~2022 年',
      skills: [
        '使用 Vue.js 進行前端開發，實現動態與互動的網頁功能',
        '開發販賣機行銷廣告遊戲，提升用戶互動性和參與感',
        '與廠商合作，利用 Event bus 串接實體販賣機設備',
        '與設計師合作，依照 Zeplin 設計稿進行精確開發，確保界面與設計一致',
        '參與團隊會議，與 PM 一同討論並研發適合販賣機平台的行銷小遊戲',
      ],
      description:
        '2019 至 2022 年於紫洣科技股份有限公司任職，負責販賣機行銷廣告開發，與販賣機廠商合作，實現與實體機台的串接。專案涉及行銷遊戲的討論與研發，並成功應用於全家超商的無人智能販賣機中，提升消費者體驗與互動性。',
      tags: ['Vue.js', 'CSS'],
      demoImgs: ['/assets/works/vending_machines.png'],
      imgs: ['/assets/works/vending_machines.png'],
    },
    {
      id: 190101,
      name: 'ALTC (長期照護媒合平台)',
      category: WorksCategoryEnum.WORK,
      date: '2018~2019 年',
      skills: [
        'PHP (Laravel) 開發SSR全端網站 RWD 響應式網頁',
        '開發新功能及後續維護',
        '資料庫建置規劃，獨立開發',
        '後端的API 撰寫',
        '規劃開發時程與時間分配',
      ],
      description:
        '2019 至 2022 年於紫洣科技股份有限公司任職，負責長照平台的全端開發，依照原有 UI設計和UX 優化開發新功能，並維護舊有系統穩定，負責首頁維護、長照機構媒合、機構資訊展示、表單申請...等功能',
      tags: ['PHP (Laravel)', 'Javascript', 'Jquery', 'CSS'],
      demoImgs: ['/assets/works/altc.png'],
      imgs: ['/assets/works/altc.png'],
      demoLinks: [
        {
          link: 'https://www.airltc.com/',
          text: '專案網站',
        },
      ],
    },
    {
      id: 190102,
      name: '桃園市社會局日照及公托資訊管理系統',
      category: WorksCategoryEnum.WORK,
      date: '2018~2019 年',
      skills: [
        '全端SSR使用C# (.Net Framework)開發，RWD 響應式網頁開發並支援 In-App-Webview',
        '資料庫建置規劃和使用 mySQL',
        'iOS APP 開發使用 Swift 及 APP 介面設計與切圖',
        '與 PM 討論規劃開發時程與時間分配',
        '與其他工程師協作開發',
        '出差到訪客戶參與處理第一線需求',
      ],
      description:
        '2019 至 2022 年於紫洣科技股份有限公司任職時開發的日照及公托資訊管理系統，負責開發和規劃整個系統，包含前後端網頁和 APP開發，並與團隊夥伴一同出差到市政府與第一線使用者討論需求和優化 UI/UX。',
      tags: [
        'C# (.Net Framework)',
        'Javascript',
        'Jquery',
        'CSS',
        'iOS APP（Swift）',
        'In-App-Webview',
        'UI/UX',
      ],
      demoImgs: ['/assets/works/taoyuan.png', '/assets/works/taoyuan_2.png'],
      imgs: ['/assets/works/taoyuan.png', '/assets/works/taoyuan_2.png'],
    },
    {
      id: 190103,
      name: '臺中市長期照顧資訊系統',
      category: WorksCategoryEnum.WORK,
      date: '2018~2019年',
      skills: [
        '全端SSR使用C# (.Net Framework)開發，RWD 響應式網頁開發並支援 In-App-Webview',
        '資料庫建置規劃和使用 mySQL',
        'iOS APP 開發使用 Swift 及 APP 介面設計與切圖',
        '與 PM 討論規劃開發時程與時間分配',
        '與其他工程師協作開發',
      ],
      description:
        '2019 至 2022 年於紫洣科技股份有限公司任職時開發的長照管理系統，負責開發和規劃整個系統，包含前後端網頁和 APP開發，並參與專案壓力測試到上線。',
      tags: ['C# (.Net Framework)', 'Javascript', 'Jquery', 'CSS', 'iOS APP（Swift）', 'UI/UX'],
      demoImgs: ['/assets/works/taichung.png', '/assets/works/taichung_2.png'],
      imgs: ['/assets/works/taichung.png', '/assets/works/taichung_2.png'],
    },
  ],
};

export const brandLogoList: Array<string> = [
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vuejs/vuejs-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nuxtjs/nuxtjs-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sass/sass-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/typescript/typescript-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/vitejs/vitejs-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/html5/html5-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/css3/css3-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/git/git-plain-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/github/github-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/gitlab/gitlab-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/figma/figma-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/sketch/sketch-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/javascript/javascript-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/java/java-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/nodejs/nodejs-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/npm/npm-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bun/bun-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/php/php-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/laravel/laravel-line-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/axios/axios-plain.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/slack/slack-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/yarn/yarn-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/webpack/webpack-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/electron/electron-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jquery/jquery-plain-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/bootstrap/bootstrap-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/netlify/netlify-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/codepen/codepen-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/mysql/mysql-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/express/express-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/solidity/solidity-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/jira/jira-original-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/swift/swift-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/photoshop/photoshop-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/illustrator/illustrator-plain.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/tailwindcss/tailwindcss-original.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/eslint/eslint-plain-wordmark.svg',
  'https://cdn.jsdelivr.net/gh/devicons/devicon@latest/icons/cypressio/cypressio-original.svg',
];
